version: '3.8'

services:
  mysql: 
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD : password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql
    restart: always

volumes:
  mysql:

networks:
  mysql: